### ISSUE TITLE
is this published on NPM?

### ISSUE THREAD

**Issue by ORESoftware** [jamestalmage/array-to-events#1]
looks like this project is used by "tap-emitter"

but I don't see the source on Github 

thx

**Comment by jamestalmage** [comment]
Yep: https://www.npmjs.com/package/array-to-events

**Comment by jamestalmage** [comment]
And yep: https://www.npmjs.com/package/tap-emitter

**Comment by ORESoftware** [comment]
ah yes, I am not sure why I asked that, I got confused earlier today, my bad
